filebeat.modules:
- module: apache
  access:
    enabled: true
    var.paths: 
    - /tmp/access.log
  error:
    enabled: true
    var.paths: 
    - /tmp/error.log

output.elasticsearch:
  hosts:
  - localhost
  protocol: http
  username: user
  password: password
  port: 9200
  index: apache
